# base image
FROM node:20.4-alpine as build

# set working directory
RUN mkdir /app
WORKDIR /app
COPY . /app

# install and cache app dependencies
COPY package.json /app/package.json

RUN npm install -g vite

RUN npm install --force

# generate build
RUN npm run build

############
### prod ###
############

# base image
FROM nginx:alpine

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# expose port 80
EXPOSE 8081

# run nginx
CMD ["nginx", "-g", "daemon off;"]

# docker build -t vue-prod -f Dockerfile-prod .
# docker run -itd -p 8081:80 vue-prod


